/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "teste.h"

int *
soma_1_svc(dados *argp, struct svc_req *rqstp)
{
	static int  result;

	result = (*argp).x + (*argp).z;

	return &result;
}

int *
subtracao_1_svc(dados *argp, struct svc_req *rqstp)
{
	static int  result;

	result = (*argp).x - (*argp).z;

	return &result;
}

int *
divisao_1_svc(dados *argp, struct svc_req *rqstp)
{
	static int  result;

	result = (*argp).x / (*argp).z;

	return &result;
}

int *
multiplicacao_1_svc(dados *argp, struct svc_req *rqstp)
{
	static int  result;

	result = (*argp).x * (*argp).z;

	return &result;
}

int *
maior_1_svc(dados *argp, struct svc_req *rqstp)
{
	static int  result;

	if ((*argp).x > (*argp).z){
		result = (*argp).x;	
	}
	else{
		result = (*argp).z;
	}
	return &result;
}

int *
potencia_1_svc(dados *argp, struct svc_req *rqstp)
{
	static int  result;

	result = (*argp).x**(*argp).z;

	return &result;
}

int *
menor_1_svc(dados *argp, struct svc_req *rqstp)
{
	static int  result;

	/* O nome ta diferente mass eu falei com o professor sobre isso, esse aqui mostra o quadrado do numero*/
	
	result = (*argp).x**2;

	return &result;
}
