/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "teste.h"


void
simp_prog_1(char *host, int x, int z, int op)
{
	CLIENT *clnt;
	int  *result_1;
	dados  soma_1_arg;
	int  *result_2;
	dados  subtracao_1_arg;
	int  *result_3;
	dados  divisao_1_arg;
	int  *result_4;
	dados  multiplicacao_1_arg;
	int  *result_5;
	dados  maior_1_arg;
	int  *result_6;
	dados  potencia_1_arg;
	int  *result_7;
	dados  menor_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMP_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (op==1){	
		soma_1_arg.x=x;
		soma_1_arg.z=z;
	 	result_1 = soma_1(&soma_1_arg, clnt);
		printf("O total da soma é: %d", *result_1);
	} else if (op==2){
		subtracao_1_arg.x=x;
		subtracao_1_arg.z=z;
		result_2 = subtracao_1(&subtracao_1_arg, clnt);
		printf ("O resultado da subtração é: %d", *result_2);
	} else if (op==3){
		multiplicacao_1_arg.x=x;
		multiplicacao_1_arg.z=z;
		result_3 = multiplicacao_1(&multiplicacao_1_arg, clnt);
		printf("O total da multiplicação é: %d", *result_3);
	}else if (op==4){
		divisao_1_arg.x=x;
		divisao_1_arg.z=z;
		result_4 = divisao_1(&divisao_1_arg, clnt);
		printf("O resultado da divisão é: %d", *result_4);
	} else if (op==5){
		maior_1_arg.x=x;
		maior_1_arg.z=z;
		result_5 = maior_1(&maior_1_arg, clnt);
		printf("O maior valor é: %d", *result_5);
	} else if (op==6){
		potencia_1_arg.x=x;
		potencia_1_arg.z=z;
		result_6 = potencia_1(&potencia_1_arg, clnt);
		printf("O total da potencia é: %d", *result_6);
	} else if (op==7){
		menor_1_arg.x=x;
		menor_1_arg.z=z;
		result_7 = maior_1(&maior_1_arg, clnt);
		printf("O resto da operacao = %d", *result_7);	
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	struct dados d;
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];


	dados.x = argv[2]

	simp_prog_1 (host);
exit (0);
}
